# Data Manipulation with Tensors

Tensor classes in deep learning frameworks resemble NumPy’s ndarray but offer automatic differentiation and GPU acceleration for faster computation.

In [2]:
import torch

A Tensor represents a multi-dimensional array of numerical values:
- 1D = vector
- 2D = matrix
- 3D = tensor
- 4D = tensor
- ...
- nD = tensor

PyTorch offers functions for creating tensors, like `torch.arange(n)`, which generates evenly spaced values.

In [7]:
y = torch.arange(10, dtype=torch.float32)
x = torch.arange(0, 12, 2, dtype=torch.float32)
print(f'tensor y => {y}')
print(f'tensor x => {x}')

tensor y => tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor x => tensor([ 0.,  2.,  4.,  6.,  8., 10.])


We can inspect the number of elements in a tensor using the `numel()` method. Our `y` tensor has 10 elements and `x` tensor has 6 elements.

In [9]:
y.numel()

10

The shape of the tensor is the length along each axis.

What is an axis? The axis corresponds to a specific dimension of the tensor. For example, in a 2D tensor (matrix), axis 0 refers to the rows and axis 1 refers to the columns.

In a 2D array we select the column (the array) by selecting an index along axis 1. Additionally we select a column by selecting which element we want from that column (from the row, we select an element from specific column e.g. (0, 1) selects the element in the first row and second column).

In [22]:
x = torch.arange(12)
x.shape

torch.Size([12])

In pytorch we can alter the shape of the tensor using the `reshape` method.

In [23]:
X = x.reshape(3,4)
X, X.shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 torch.Size([3, 4]))

we can also infer one of the dimensions by setting it to -1. This tells PyTorch to automatically calculate the appropriate size for that dimension based on the total number of elements and the other specified dimensions.

In [25]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
x.reshape(4, -1)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

We can also initialize tensors using torch.zeros() and torch.ones() functions.


In [27]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])