# Numpy Tutorial

In [61]:
import numpy as np

In [62]:
L = [1,2,3]
A = np.array([1,2,3])

In [63]:
for e in L:
    print(e)

1
2
3


In [64]:
for e in A:
  print(e)

1
2
3


As we can see we can instantiate a list and an Array and also iterate through them in the same way.

Let's proceed with another one common operation in list/arrays, to append/add an element to the list/array

In [65]:
L.append(4)
L

[1, 2, 3, 4]

In [66]:
A.append(4)
A

AttributeError: 'numpy.ndarray' object has no attribute 'append'

Why is that error?

Generally speaking the size of a list can change but the size of an array can't change. If you want to update an array, you will have to create a new one with the exact same elements  + the updated/appended element(s).

Why is that? -> Because in Deep Learning `memory` and `efficiency` (recall memory management, data structures and algorithms theory) are crucial.

Let's consider a similar scenario were we can try to add an item on the list.

In [67]:
L + [5]

[1, 2, 3, 4, 5]

In lists, this plus operation means just: concatenate

In [68]:
A + np.array(5)

array([6, 7, 8])

On the other hand, this operation is not the same when it comes to arrays, in arrays it adds them up element-wise. 

In numpy we call this `broadcasting`.

Technically in maths, this is an illegal operation -> `you cannot add two vectors of different sizes`. However in numpy this makes total sense.

Why is this allowed in numpy? Again efficiency comes to the forefront. By allowing this kind of operations we can leverage the underlying hardware more effectively, leading to faster computations and reduced memory usage. For example, imagine if you had to add a 5 to all the elements of `A`, you could do it in a single operation without the need for an explicit loop, or creating an new numpy array of the same size.


Another one important reason why operations such as `A + np.array(5)` are allowed in numpy is that Numpy is all about doing Maths. Thats why in Python Lists you dont have such a capability

## Vector Addition

In [69]:
A + np.array([4,5,6])

array([5, 7, 9])

As you can see now numpy was smart enough to do also vector addition, since the two arrays were of the same size.

Note how intelligent broadcasting is in Numpy, it automatically expands the dimensions of the smaller array to match the larger array, allowing for element-wise operations without the need for explicit loops.

In [70]:
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Of course this makes sense, because you cannot add vectors of different sizes.

In [71]:
A * 5

array([ 5, 10, 15])

As expected does the mathematical operations

In [72]:
L * 5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

List L is repeated 5 times. So in lists the multiply operation does repetition, while for arrays it does multiplication.

In [73]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In Python Lists though, how do we add aanything to each element in the list?

2 ways:
- For loop (by creating new list)
- List comprehension

In [74]:
L2 = []
for e in L:
  L2.append(e + 1)

In [75]:
L2 = [e + 1 for e in L]
L2

[2, 3, 4, 5]

One nice thing about this is that it can be very flexible. 

e.g. how to square everything in L?

In [76]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [77]:
[e**2 for e in L]

[1, 4, 9, 16]

In numpy this is way easier.

In [78]:
A**2

array([1, 4, 9])

In numpy if we apply a function to a numpy array, it applies the function element-wise (most of the time).

In [79]:
np.power(A, 2)

array([1, 4, 9])

In [80]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [81]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [82]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

## Dot Product

$\mathbf{a} \cdot \mathbf{b} = a^T b = \sum_{i=1}^{n} a_i b_i$

In [83]:
a = np.array([1,2])
b = np.array([3,4])

In [84]:
dot = 0

for e, f in zip(a, b):
  dot += e * f

dot

np.int64(11)

In [85]:
a * b

array([3, 8])

In [86]:
np.sum(a * b) # dot product

np.int64(11)

In [87]:
(a*b).sum()

np.int64(11)

In [88]:
np.dot(a, b)

np.int64(11)

In [89]:
a.dot(b)

np.int64(11)

In [90]:
a@b

np.int64(11)

In [91]:
maga = np.sqrt((a*a).sum())
magb = np.sqrt((b*b).sum())
print(f'magnitude_a {magnitude_a}')
print(f'magnitude_b {magnitude_b}')

cos_theta = np.dot(a,b) / (magnitude_a * magnitude_b)
cos_theta

magnitude_a 2.23606797749979
magnitude_b 5.0


np.float64(0.9838699100999074)

In [92]:
# To get the angle we do arccos since we got the cosine of theh angle
theta = np.arccos(cos_theta)
theta

np.float64(0.17985349979247847)

##  Matrices

In [93]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [94]:
L[0]

[1, 2]

In [95]:
L[0][1]

2

In [96]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

Bellow we select the first column of the first row.

In [98]:
A[0][1], A[0,1]

(np.int64(2), np.int64(2))

But, what if i want to return the column at index 0? Numpy has a smart way of doing this.

We can just select the column using the following syntax:

```python
column_0 = matrix[:, 0]
```

What that means is we are selecting all rows (:) and the first column (0) of the matrix.

In [ ]:
A[:, 0]

With numpy we can get the Transpose of a matrix using simple methods

In [99]:
A.T

array([[1, 3],
       [2, 4]])

In [100]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [102]:
try_with_list = np.exp(L)
try_with_list, type(try_with_list)

(array([[ 2.71828183,  7.3890561 ],
        [20.08553692, 54.59815003]]),
 numpy.ndarray)

### Matrix Multiplication

In [103]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

Matrix multiplication is a fundamental operation in linear algebra, and it can be performed in numpy using the `@` operator or the `np.dot()` function.

Here's an example of matrix multiplication using the `@` operator:

```python
result = matrix_a @ matrix_b
```

And here's the same operation using `np.dot()`:

```python
result = np.dot(matrix_a, matrix_b)
```

Both of these methods will give you the same result.

Also the inner dimensions of the matrices must match for multiplication to be possible. This means that if `matrix_a` is of shape `(m, n)` then `matrix_b` must be of shape `(n, p)` for some `p`. The resulting matrix will then have the shape `(m, p)`.

In [104]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

Let's se what happens if we break that rule

In [105]:
B.dot(A)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [106]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [107]:
A = np.array([[1,2], [3,4]])
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [109]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [113]:
I = np.linalg.inv(A) @ A
I

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

Why we have these numbers there? Because in computers we cannot be exact, and the algorithms we use to calculate such values often involve approximations and floating-point arithmetic, which can introduce small errors.

In [115]:
np.trace(A) # Calculates the main diagonal

np.int64(5)

In [117]:
np.diag(A)

array([1, 4])

In [118]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

So keep in mind that this function is overloaded.

In [119]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [126]:
Lam, V = np.linalg.eig(A)
print(Lam)
print('--')
print(V)

[-0.37228132  5.37228132]
--
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [124]:
V, V[:, 0]

(array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]),
 array([-0.82456484,  0.56576746]))

In [ ]:
V[:, 0] * Lam[0]

## Solving Linear Systems

In [131]:
A = np.array([[1,1], [1.5, 4]])
b = np.array([2200, 5050])
A, b

(array([[1. , 1. ],
        [1.5, 4. ]]),
 array([2200, 5050]))

In [130]:
np.linalg.solve(A, b)

array([1500.,  700.])

We can solve the same system using the exact mathematical way (by using the inverse) markdown:

$$
Ax = b  \Rightarrow  x = A^{-1}b
$$